### ISSUE TITLE
Non-compat with CheckoutWC

### ISSUE THREAD

**Issue by martinowren** [Dintero/Dintero.Checkout.WooCommerce.V2#91]
Hello!

We are trying to use this plugin alongside [CheckoutWC](https://www.checkoutwc.com/), but it does not seem to work. 

I think it is due to the way the plugin injects data into the checkout page. 

You can contact me on kontakt@russemerket.no if you want help debugging on a live site.

**Comment by andersem** [comment]
We've done some investigation.

It seems CheckoutWC and Dintero Redirect works, it's just with Dintero Embedded that it doesn't.

CheckoutWC has added compatibility with some other payment providers in their plugin, but not for Dintero, that's why you might see that the embedded solution works for other payment providers.

**Comment by martinowren** [comment]
Hello @andersem !

This compat layer that they have done for other plugins would not help this dintero plugin. 

The plugin is doing some pretty whacky stuff to output its UI.

Instead of using the normal WP methodology for outputting UI, it is attempting to detect and replace the entire woocommerce/templates/checkout/payment.php template. But CheckoutWC doesn't load that template so it can't replace it.

There's no reason for this technologically in fact it creates bugs on the regular checkout page too. Once Dintero is selected all other payment methods stop appearing.

**Comment by andersem** [comment]
That depends entirely on which form factor you choose. If you choose the redirect-option, we don't change the payment template.

For the embedded form factor we do change the template, but it's no different from what Klarna Checkout does. The compatibility layer with Klarna Checkout is mostly just a button to load the Klarna template directly.

I think the best option is to look at using the redirect-option with CheckoutWC.

**Comment by martinowren** [comment]
Hi Anders!

Unfortunately, a redirect to payment is very ineffective when it comes to the checkout conversion rate. When we have used redirect-based flows before, we have seen a 2-3% drop in conversions which is a killer for us. 

Regarding the klarna checkout. I don know if we are talking about the same plugin, but the klarna payment gateway does not have this behavior. Maybe you might be talking about the klarna service that replaces the whole checkout?

**Comment by NiklasHogefjord** [comment]
Hi @martinowren,
Klarna Checkout is the plugin that replaces the majority of the checkout page (with its own template file). Klarna Payments have a setup where it's displayed more as a regular payment method in WooCommerce checkout page.

Dintero have a flow that is similar to Klarna Payments, but that flow results in Dintero controlling the _Place order_ button (instead of WooCommerce).

To conclude - if you want to use CheckoutWC, the redirect flow is currently your only option.

**Comment by martinowren** [comment]
Okay, thanks for the comments. Will have to drop Dintero for now.
